# Generated by Django 5.0.6 on 2026-06-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_goal'),
        ('goals', '0002_goal_assigned_exercises'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressrecord',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_logs', to='goals.goal'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='hold_time_sec',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
