# Generated by Django 5.0.6 on 2026-06-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progressrecord_exercise_progressrecord_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressrecord',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='hold_time_sec',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='progressrecord',
            name='reps',
        ),
    ]
