# Generated by Django 5.0.6 on 2026-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('lean', 'Lean'), ('average', 'Average'), ('stocky', 'Stocky')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_goal',
            field=models.CharField(blank=True, choices=[('calisthenics_body', 'Calisthenics Body'), ('v_taper', 'V-Taper'), ('weight_loss', 'Weight Loss'), ('general_fitness', 'General Fitness')], max_length=30),
        ),
    ]
