# Generated by Django 5.0.6 on 2026-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_body_type_profile_selected_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_focus',
            field=models.CharField(blank=True, choices=[('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('core', 'Core Stability'), ('pull_strength', 'Pull Strength'), ('push_strength', 'Push Strength'), ('mobility', 'Mobility')], max_length=30),
        ),
    ]
