# Generated by Django 5.0.6 on 2026-06-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_goal_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_goal',
            field=models.CharField(blank=True, choices=[('calisthenics_body', 'Calisthenics Body'), ('v_taper', 'V-Taper'), ('weight_loss', 'Weight Loss'), ('general_fitness', 'General Fitness'), ('my_plan', 'My Plan')], max_length=30),
        ),
    ]
