# Generated by Django 5.0.6 on 2026-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_selected_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height_cm',
        ),
        migrations.AddField(
            model_name='profile',
            name='height_ft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Height (ft)'),
        ),
    ]
