from django.test import TestCase
from django.urls import reverse

from .models import FitnessIcon, InspirationCategory, MotivationQuote


class InspirationModelTests(TestCase):
    def setUp(self):
        self.cat = InspirationCategory.objects.create(
            name='Bodybuilding',
            description='Stage-ready athletes',
            icon='💪',
            accent='emerald',
        )
        self.icon = FitnessIcon.objects.create(
            name='Arnold S',
            nickname='Oak',
            category=self.cat,
            short_bio='Iconic bodybuilder',
            bio='Long form biography paragraph.',
            image_url='https://images.unsplash.com/photo-1',
            achievements='Mr. Olympia x7\nMr. Universe x5',
            training_tips='Train heavy\nEat big',
            signature_quote='Strength does not come from winning.',
            video_url='https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        )

    def test_category_str(self):
        self.assertEqual(str(self.cat), 'Bodybuilding')

    def test_category_slug_autogenerated(self):
        self.assertEqual(self.cat.slug, 'bodybuilding')

    def test_icon_str_and_slug(self):
        self.assertEqual(str(self.icon), 'Arnold S')
        self.assertEqual(self.icon.slug, 'arnold-s')

    def test_achievement_and_tip_lists(self):
        self.assertEqual(self.icon.achievement_list, ['Mr. Olympia x7', 'Mr. Universe x5'])
        self.assertEqual(self.icon.tip_list, ['Train heavy', 'Eat big'])

    def test_youtube_id_and_embed(self):
        self.assertEqual(self.icon.youtube_id, 'dQw4w9WgXcQ')
        self.assertEqual(self.icon.youtube_embed_url, 'https://www.youtube.com/embed/dQw4w9WgXcQ')

    def test_youtube_id_short_url(self):
        self.icon.video_url = 'https://youtu.be/abc12345xyz'
        self.icon.save()
        self.assertEqual(self.icon.youtube_id, 'abc12345xyz')
        self.assertIn('abc12345xyz', self.icon.youtube_embed_url)

    def test_youtube_id_empty(self):
        self.icon.video_url = ''
        self.icon.save()
        self.assertEqual(self.icon.youtube_id, '')
        self.assertEqual(self.icon.youtube_embed_url, '')

    def test_quote_str(self):
        q = MotivationQuote.objects.create(
            text='Stay hungry, stay foolish.',
            author='Someone',
            category=self.cat,
            icon=self.icon,
        )
        self.assertIn('Stay hungry', str(q))

    def test_quote_is_featured_default(self):
        q = MotivationQuote.objects.create(text='Push through', author='Coach')
        self.assertFalse(q.is_featured)


class InspirationViewTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.cat = InspirationCategory.objects.create(
            name='Strength',
            description='Lifters',
            icon='🏋️',
            accent='amber',
        )
        cls.icon = FitnessIcon.objects.create(
            name='Ronnie C',
            nickname='The King',
            category=cls.cat,
            short_bio='8x Mr. Olympia',
            bio='Paraphrased biography.',
            image_url='https://images.unsplash.com/photo-2',
            signature_quote='Yeah buddy!',
            achievements='Mr. Olympia x8',
            training_tips='Light weight, baby!',
        )
        MotivationQuote.objects.create(
            text='Yeah buddy, light weight baby!',
            author='Ronnie C',
            category=cls.cat,
            icon=cls.icon,
            is_featured=True,
        )

    def test_feed_loads(self):
        resp = self.client.get(reverse('inspiration-feed'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Inspiration')
        self.assertContains(resp, 'Browse all icons')
        self.assertContains(resp, 'Ronnie C')

    def test_icon_list_all(self):
        resp = self.client.get(reverse('inspiration-icons'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Ronnie C')
        self.assertContains(resp, 'The King')

    def test_icon_list_filter_by_category(self):
        resp = self.client.get(reverse('inspiration-icons') + '?category=strength')
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Ronnie C')

    def test_icon_detail_loads(self):
        resp = self.client.get(reverse('inspiration-icon-detail', args=[self.icon.slug]))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Ronnie C')
        self.assertContains(resp, 'Mr. Olympia x8')
        self.assertContains(resp, 'Light weight, baby!')
        self.assertContains(resp, 'Yeah buddy!')

    def test_icon_detail_404(self):
        resp = self.client.get(reverse('inspiration-icon-detail', args=['nope']))
        self.assertEqual(resp.status_code, 404)

    def test_quote_wall(self):
        resp = self.client.get(reverse('inspiration-quotes'))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Yeah buddy, light weight baby!')

    def test_quote_wall_filter(self):
        resp = self.client.get(reverse('inspiration-quotes') + '?category=strength')
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Yeah buddy, light weight baby!')

    def test_random_quote_api(self):
        resp = self.client.get(reverse('inspiration-random-quote'))
        self.assertEqual(resp.status_code, 200)
        data = resp.json()
        self.assertIn('text', data)
        self.assertIn('author', data)
        self.assertEqual(data['author'], 'Ronnie C')

    def test_random_quote_filtered(self):
        resp = self.client.get(reverse('inspiration-random-quote') + '?icon=ronnie-c')
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.json()['icon_slug'], 'ronnie-c')
