# Generated by Django 5.0.6 on 2026-06-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image', upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL (e.g. Unsplash)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL (e.g. Unsplash)'),
        ),
    ]
