# Generated by Django 5.0.6 on 2026-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('outfit', 'Outfit Products'), ('exercise', 'Exercise Products'), ('nutrition', 'Nutrition Products')], default='outfit', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
