# Generated by Django 5.0.6 on 2026-06-03 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('calisthenics', 'Calisthenics Physique'), ('lean_athletic', 'Lean Athletic Body'), ('muscle_gain', 'Muscle Gain'), ('lean_bulk', 'Lean Bulk'), ('fat_loss', 'Fat Loss'), ('recomp', 'Body Recomposition'), ('strength', 'Strength Training'), ('general', 'General Fitness')], max_length=40)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timeline_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
