# Generated by Django 5.0.6 on 2026-06-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_goal'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assigned_exercises',
            field=models.ManyToManyField(blank=True, related_name='assigned_goals', to='exercises.exercise'),
        ),
    ]
