# Generated by Django 5.0.6 on 2026-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='goal',
            field=models.CharField(choices=[('general', 'General'), ('strength', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('endurance', 'Endurance'), ('mobility', 'Mobility'), ('flexibility', 'Flexibility'), ('weight_loss', 'Weight Loss')], default='general', max_length=30),
        ),
    ]
