# Generated by Django 5.0.6 on 2026-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercisecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='calories_per_set',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='exercise',
            name='default_reps',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='default_sets',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration_min',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
