# Generated by Django 5.0.6 on 2026-06-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_calories_per_set_exercise_default_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image', upload_to='exercises/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL (e.g. Unsplash)'),
        ),
    ]
