"""Seed the exercises library with a comprehensive catalog of movements.

Covers all muscle categories, difficulty levels, equipment types, and goal types
so the recommendation engine has enough data to surface useful suggestions
regardless of a user's selected goal.
"""
from django.core.management.base import BaseCommand
from exercises.models import Exercise


EXERCISES = [
    # ---------- CHEST ----------
    {
        'name': 'Push-Up',
        'category': 'chest',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight',
        'goal': 'general',
        'default_reps': 15, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 7,
        'target_muscles': 'Chest, Anterior Deltoids, Triceps, Core',
        'description': 'The foundational bodyweight push. Builds chest endurance, shoulder stability, and core bracing.',
        'steps': "Setup: Begin in a high plank, hands under shoulders, body in a straight line from head to heels.\nMovement: Lower your chest to within a fist-width of the floor, keeping elbows tracking at ~45 degrees. Press back to the start, exhaling as you push.",
        'form_tips': "Keep your core tight and hips level — don't let your low back sag or pike up.",
        'breathing': 'Inhale on the way down, exhale forcefully on the press up.',
        'common_mistakes': 'Flaring elbows to 90°, sagging hips, or partial range of motion.',
        'safety': 'Drop to knees if form breaks; stop if you feel sharp shoulder pain.',
    },
    {
        'name': 'Incline Dumbbell Press',
        'category': 'chest',
        'difficulty': 'intermediate',
        'equipment': 'Dumbbells, Adjustable Bench',
        'goal': 'hypertrophy',
        'default_reps': 10, 'default_sets': 4, 'duration_min': 8, 'calories_per_set': 11,
        'target_muscles': 'Upper Chest, Front Delts, Triceps',
        'description': 'Targets the upper (clavicular) head of the pec for a fuller, lifted chest.',
        'steps': "Setup: Set a bench to 30–45°. Sit with dumbbells on thighs, then lie back and bring them to shoulder level.\nMovement: Press the dumbbells up until arms are extended, then lower with control to a deep stretch.",
        'form_tips': "Drive feet into the floor, keep wrists stacked over elbows, and pause briefly at the top.",
        'breathing': 'Inhale lowering, exhale pressing.',
        'common_mistakes': 'Bouncing off the bottom, using legs to kick the weight up, or flaring elbows.',
        'safety': 'Use a spotter or safety arms for heavy sets.',
    },
    {
        'name': 'Barbell Bench Press',
        'category': 'chest',
        'difficulty': 'advanced',
        'equipment': 'Barbell, Bench, Rack',
        'goal': 'strength',
        'default_reps': 5, 'default_sets': 5, 'duration_min': 12, 'calories_per_set': 14,
        'target_muscles': 'Chest, Triceps, Front Delts',
        'description': 'The classic strength benchmark for upper body pushing power.',
        'steps': "Setup: Lie on a flat bench, retract shoulder blades, grip the bar slightly wider than shoulders.\nMovement: Unrack, lower the bar to mid-chest with control, then press to lockout.",
        'form_tips': "Drive feet down, keep upper back tight, and tuck elbows to ~75° from the torso.",
        'breathing': 'Big breath and brace at the top, hold through the rep, reset between reps.',
        'common_mistakes': 'Bouncing the bar off the chest, lifting feet, or flaring elbows to 90°.',
        'safety': 'Always use a spotter or safety pins set just above chest level.',
    },
    {
        'name': 'Dip',
        'category': 'chest',
        'difficulty': 'intermediate',
        'equipment': 'Parallel Bars',
        'goal': 'strength',
        'default_reps': 8, 'default_sets': 3, 'duration_min': 5, 'calories_per_set': 10,
        'target_muscles': 'Lower Chest, Triceps, Front Delts',
        'description': 'A heavy pressing staple that builds chest, triceps, and shoulder control.',
        'steps': "Setup: Start at the top of the dip bars, arms locked, shoulders down and back.\nMovement: Lower until upper arms are parallel to the floor (or just below), then press back to lockout.",
        'form_tips': "Lean torso slightly forward to bias chest; keep shoulders packed — don't shrug.",
        'breathing': 'Inhale on the descent, exhale as you press up.',
        'common_mistakes': 'Going too deep and stressing the shoulder, or shrugging at the top.',
        'safety': 'Stop short of shoulder pain; use a band for assistance if needed.',
    },

    # ---------- BACK ----------
    {
        'name': 'Pull-Up',
        'category': 'back',
        'difficulty': 'intermediate',
        'equipment': 'Pull-Up Bar',
        'goal': 'strength',
        'default_reps': 6, 'default_sets': 4, 'duration_min': 6, 'calories_per_set': 12,
        'target_muscles': 'Lats, Biceps, Mid Back, Rear Delts',
        'description': 'The king of back exercises. Builds a wide, strong back and serious relative strength.',
        'steps': "Setup: Hang from a bar with hands slightly wider than shoulders, palms facing away.\nMovement: Pull until your chin clears the bar, leading with the chest, then lower with control to a full hang.",
        'form_tips': "Initiate the pull by driving elbows down toward your hips, not by bending the arms first.",
        'breathing': 'Exhale pulling up, inhale lowering.',
        'common_mistakes': 'Kipping, half reps, or shrugging shoulders up by the ears.',
        'safety': 'Use a band for assistance or negatives to build toward a first strict rep.',
    },
    {
        'name': 'Chin-Up',
        'category': 'back',
        'difficulty': 'intermediate',
        'equipment': 'Pull-Up Bar',
        'goal': 'hypertrophy',
        'default_reps': 8, 'default_sets': 3, 'duration_min': 5, 'calories_per_set': 11,
        'target_muscles': 'Lats, Biceps, Mid Back',
        'description': 'A supinated grip variation that emphasizes biceps alongside the back.',
        'steps': "Setup: Hang from a bar with palms facing you, hands shoulder-width.\nMovement: Pull your chin above the bar, then lower under control.",
        'form_tips': "Squeeze the bar and think about pulling your elbows to your ribs.",
        'breathing': 'Exhale up, inhale down.',
        'common_mistakes': 'Swinging or using momentum to cheat the rep.',
        'safety': 'Stop short of elbow or shoulder pain; use a band if needed.',
    },
    {
        'name': 'Barbell Bent-Over Row',
        'category': 'back',
        'difficulty': 'intermediate',
        'equipment': 'Barbell',
        'goal': 'strength',
        'default_reps': 8, 'default_sets': 4, 'duration_min': 9, 'calories_per_set': 13,
        'target_muscles': 'Mid Back, Lats, Biceps, Rear Delts',
        'description': 'A heavy compound row that builds thickness through the entire back.',
        'steps': "Setup: Hinge to ~45° with a flat back, grip the bar just outside the knees.\nMovement: Row the bar to your lower chest/upper abs, squeezing the shoulder blades together.",
        'form_tips': "Keep the back flat — hinge from the hips, not the waist. Pause briefly at the top.",
        'breathing': 'Exhale on the pull, inhale on the lower.',
        'common_mistakes': 'Rounding the lower back or yanking the bar with the hips.',
        'safety': 'Use a light weight to master the hinge before loading.',
    },
    {
        'name': 'Lat Pulldown',
        'category': 'back',
        'difficulty': 'beginner',
        'equipment': 'Cable Machine',
        'goal': 'hypertrophy',
        'default_reps': 12, 'default_sets': 3, 'duration_min': 5, 'calories_per_set': 9,
        'target_muscles': 'Lats, Biceps, Mid Back',
        'description': 'A cable staple for building lat width with adjustable resistance.',
        'steps': "Setup: Sit at the machine, thighs anchored, grip the bar slightly wider than shoulders.\nMovement: Pull the bar to your upper chest, driving elbows down and back.",
        'form_tips': "Resist the urge to lean back excessively; the torso should move only slightly.",
        'breathing': 'Exhale pulling, inhale returning.',
        'common_mistakes': 'Pulling behind the neck (shoulder stress) or yanking with the lower back.',
        'safety': 'Avoid behind-the-neck variations to protect rotator cuff.',
    },
    {
        'name': 'Inverted Row',
        'category': 'back',
        'difficulty': 'beginner',
        'equipment': 'Bar, Rack, or TRX',
        'goal': 'general',
        'default_reps': 10, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 8,
        'target_muscles': 'Mid Back, Biceps, Rear Delts, Core',
        'description': 'A horizontal pull that teaches the rowing pattern with adjustable difficulty.',
        'steps': "Setup: Set a bar at hip height, lie underneath, and grip it with a shoulder-width overhand grip.\nMovement: Pull your chest to the bar, squeezing the shoulder blades, then lower with control.",
        'form_tips': "Keep the body in a straight plank line — don't let hips sag or pike.",
        'breathing': 'Exhale pulling, inhale lowering.',
        'common_mistakes': 'Piking the hips up to make it easier.',
        'safety': 'Lower the bar to make the move easier, raise it to make it harder.',
    },

    # ---------- SHOULDERS ----------
    {
        'name': 'Overhead Press',
        'category': 'shoulders',
        'difficulty': 'intermediate',
        'equipment': 'Barbell',
        'goal': 'strength',
        'default_reps': 6, 'default_sets': 4, 'duration_min': 8, 'calories_per_set': 12,
        'target_muscles': 'Deltoids, Triceps, Upper Traps, Core',
        'description': 'The premier vertical press for building strong, capped shoulders.',
        'steps': "Setup: Rack the bar at clavicle level, grip just outside shoulders, elbows slightly forward.\nMovement: Brace the core and press the bar overhead, finishing with biceps by the ears.",
        'form_tips': "Squeeze glutes and brace abs hard to protect the lower back.",
        'breathing': 'Inhale at the rack, exhale pressing, inhale at the top before lowering.',
        'common_mistakes': 'Excessive back arch, flaring elbows, or pressing in front of the face.',
        'safety': 'Start light to nail the lockout position before going heavy.',
    },
    {
        'name': 'Dumbbell Lateral Raise',
        'category': 'shoulders',
        'difficulty': 'beginner',
        'equipment': 'Dumbbells',
        'goal': 'hypertrophy',
        'default_reps': 15, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 6,
        'target_muscles': 'Lateral Delts, Upper Traps',
        'description': 'An isolation move that builds the width of the shoulders for a 3D look.',
        'steps': "Setup: Stand tall with dumbbells at your sides, a slight bend in the elbows.\nMovement: Raise the dumbbells out to the sides until arms are parallel with the floor, then lower with control.",
        'form_tips': "Lead with the elbows, keep the pinkies slightly higher than the thumbs.",
        'breathing': 'Exhale on the way up, inhale lowering.',
        'common_mistakes': 'Shrugging, swinging, or using momentum to throw the weight up.',
        'safety': 'Use a weight that lets you control the entire range — ego lifting ruins the stimulus.',
    },
    {
        'name': 'Pike Push-Up',
        'category': 'shoulders',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight',
        'goal': 'strength',
        'default_reps': 10, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 8,
        'target_muscles': 'Front Delts, Triceps, Upper Chest',
        'description': 'A bodyweight vertical press that builds toward a handstand push-up.',
        'steps': "Setup: Start in a downward dog position, hips high, hands and feet on the floor.\nMovement: Bend the elbows to lower the crown of your head toward the floor, then press back up.",
        'form_tips': "Keep hips stacked over the shoulders, not the hands, to load the delts properly.",
        'breathing': 'Inhale down, exhale up.',
        'common_mistakes': 'Bending the hips so the move becomes a regular push-up.',
        'safety': 'Place a folded towel under the head to cushion the floor.',
    },
    {
        'name': 'Face Pull',
        'category': 'shoulders',
        'difficulty': 'beginner',
        'equipment': 'Cable Machine, Rope Attachment',
        'goal': 'general',
        'default_reps': 15, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 6,
        'target_muscles': 'Rear Delts, Mid Traps, Rotator Cuff',
        'description': 'The go-to move for shoulder health, posture, and rear delt development.',
        'steps': "Setup: Set a cable to upper-chest height with a rope attachment.\nMovement: Pull the rope to your forehead, externally rotating at the end so your hands finish by your ears.",
        'form_tips': "Squeeze the rear delts and don't yank with the lower back.",
        'breathing': 'Exhale on the pull, inhale on the return.',
        'common_mistakes': 'Using too much weight and using the lower back to pull.',
        'safety': 'Light weight, high reps — this is a health and posture move.',
    },

    # ---------- ARMS ----------
    {
        'name': 'Dumbbell Bicep Curl',
        'category': 'arms',
        'difficulty': 'beginner',
        'equipment': 'Dumbbells',
        'goal': 'hypertrophy',
        'default_reps': 12, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 6,
        'target_muscles': 'Biceps, Forearms',
        'description': 'A classic isolation move for building sleeve-filling biceps.',
        'steps': "Setup: Stand with dumbbells at your sides, palms forward, elbows tucked.\nMovement: Curl the weights to your shoulders, squeezing at the top, then lower under control.",
        'form_tips': "Pin your elbows to your ribs and avoid swinging the torso.",
        'breathing': 'Exhale curling, inhale lowering.',
        'common_mistakes': 'Swinging the body, using momentum, or letting the shoulders roll forward.',
        'safety': 'Choose a weight that lets you keep strict form throughout the set.',
    },
    {
        'name': 'Tricep Pushdown',
        'category': 'arms',
        'difficulty': 'beginner',
        'equipment': 'Cable Machine, Straight or Rope Bar',
        'goal': 'hypertrophy',
        'default_reps': 12, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 6,
        'target_muscles': 'Triceps',
        'description': 'A high-rep isolation staple for horseshoe triceps.',
        'steps': "Setup: Set the cable to upper-chest height, grip the bar or rope, elbows pinned to your sides.\nMovement: Extend the elbows to press the bar/rope toward your thighs, pause, then return.",
        'form_tips': "Keep elbows stationary — only the forearms should move.",
        'breathing': 'Exhale on the press, inhale returning.',
        'common_mistakes': 'Letting the elbows drift forward or using the shoulders to push.',
        'safety': 'Use a controlled tempo; ego lifting wastes the stimulus.',
    },
    {
        'name': 'Hammer Curl',
        'category': 'arms',
        'difficulty': 'beginner',
        'equipment': 'Dumbbells',
        'goal': 'hypertrophy',
        'default_reps': 12, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 6,
        'target_muscles': 'Brachialis, Biceps, Forearms',
        'description': 'A neutral-grip curl that adds thickness to the upper arm and forearms.',
        'steps': "Setup: Stand with dumbbells at your sides, palms facing each other.\nMovement: Curl the weights up, keeping the neutral grip, then lower with control.",
        'form_tips': "Don't rotate the wrist — keep palms facing throughout.",
        'breathing': 'Exhale curling, inhale lowering.',
        'common_mistakes': 'Flipping the wrist to turn it into a regular curl.',
        'safety': 'Reduce range of motion if you feel wrist strain.',
    },
    {
        'name': 'Close-Grip Push-Up',
        'category': 'arms',
        'difficulty': 'intermediate',
        'equipment': 'Bodyweight',
        'goal': 'strength',
        'default_reps': 12, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 8,
        'target_muscles': 'Triceps, Chest, Front Delts',
        'description': 'A push-up variation that hammers the triceps while still working the chest.',
        'steps': "Setup: Get into a push-up position with hands directly under the chest, almost touching.\nMovement: Lower until your chest nearly grazes your hands, then press back up.",
        'form_tips': "Keep elbows tight to the ribs — they should brush your sides on the way down.",
        'breathing': 'Inhale down, exhale up.',
        'common_mistakes': 'Hands drifting too far forward, turning it into a normal push-up.',
        'safety': 'Drop to knees if the depth or reps become too challenging.',
    },

    # ---------- LEGS ----------
    {
        'name': 'Bodyweight Squat',
        'category': 'legs',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight',
        'goal': 'general',
        'default_reps': 20, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 8,
        'target_muscles': 'Quads, Glutes, Hamstrings, Core',
        'description': 'The foundational lower-body pattern — hip and knee control under load.',
        'steps': "Setup: Stand with feet shoulder-width, toes pointed slightly out.\nMovement: Push the hips back and bend the knees to lower until thighs are at least parallel to the floor, then drive back up.",
        'form_tips': "Knees track over toes, chest stays up, weight stays in the mid-foot.",
        'breathing': 'Inhale descending, exhale standing up.',
        'common_mistakes': 'Knees caving inward, heels lifting, or excessive forward lean.',
        'safety': 'Reduce depth if you feel pinching in the knees or lower back.',
    },
    {
        'name': 'Barbell Back Squat',
        'category': 'legs',
        'difficulty': 'advanced',
        'equipment': 'Barbell, Squat Rack',
        'goal': 'strength',
        'default_reps': 5, 'default_sets': 5, 'duration_min': 12, 'calories_per_set': 16,
        'target_muscles': 'Quads, Glutes, Hamstrings, Core, Upper Back',
        'description': 'The king of leg exercises — total-body strength and muscle builder.',
        'steps': "Setup: Set the bar in a high- or low-bar position, step out, and stand with feet shoulder-width.\nMovement: Brace, sit back and down until thighs are at least parallel, then drive up through the mid-foot.",
        'form_tips': "Brace hard, keep the chest up, and drive elbows down to keep the upper back tight.",
        'breathing': 'Big breath and brace at the top, hold through the rep, reset between reps.',
        'common_mistakes': 'Knees caving, rounding the lower back, or rising onto the toes.',
        'safety': 'Use safety pins set just below your bottom position; never squat in a cage without them.',
    },
    {
        'name': 'Walking Lunge',
        'category': 'legs',
        'difficulty': 'intermediate',
        'equipment': 'Bodyweight or Dumbbells',
        'goal': 'general',
        'default_reps': 12, 'default_sets': 3, 'duration_min': 6, 'calories_per_set': 11,
        'target_muscles': 'Quads, Glutes, Hamstrings, Calves',
        'description': 'A unilateral leg move that builds single-leg strength, balance, and control.',
        'steps': "Setup: Stand tall, then step one foot forward.\nMovement: Lower the back knee toward the floor, then drive off the front heel to bring the back leg forward into the next lunge.",
        'form_tips': "Keep the front knee tracking over the middle toe; torso upright.",
        'breathing': 'Inhale lowering, exhale stepping up.',
        'common_mistakes': 'Front knee collapsing inward, or short choppy steps.',
        'safety': 'Hold dumbbells at your sides for added load once bodyweight is easy.',
    },
    {
        'name': 'Romanian Deadlift',
        'category': 'legs',
        'difficulty': 'intermediate',
        'equipment': 'Barbell or Dumbbells',
        'goal': 'hypertrophy',
        'default_reps': 10, 'default_sets': 3, 'duration_min': 8, 'calories_per_set': 13,
        'target_muscles': 'Hamstrings, Glutes, Lower Back',
        'description': 'A hip-hinge pattern that builds hamstring and glute strength through a long range.',
        'steps': "Setup: Stand with feet hip-width, holding a bar in front of your thighs.\nMovement: Push hips back, keeping a soft knee, lowering the bar along your legs until you feel a deep hamstring stretch, then drive hips forward to stand.",
        'form_tips': "Keep the bar close to the body and the back flat — hinge from the hips, not the waist.",
        'breathing': 'Inhale lowering, exhale standing up.',
        'common_mistakes': 'Rounding the lower back or letting the bar drift away from the legs.',
        'safety': 'Choose a load that lets you maintain a neutral spine throughout.',
    },
    {
        'name': 'Glute Bridge',
        'category': 'legs',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight or Barbell',
        'goal': 'general',
        'default_reps': 15, 'default_sets': 3, 'duration_min': 3, 'calories_per_set': 6,
        'target_muscles': 'Glutes, Hamstrings, Core',
        'description': 'An entry-level hip-extension move that teaches glute activation.',
        'steps': "Setup: Lie on your back, knees bent, feet flat on the floor hip-width apart.\nMovement: Drive through the heels to lift the hips toward the ceiling, squeezing the glutes at the top.",
        'form_tips': "Don't hyperextend the lower back — finish the rep with a strong glute squeeze.",
        'breathing': 'Exhale lifting, inhale lowering.',
        'common_mistakes': 'Pushing with the lower back instead of the glutes.',
        'safety': 'Place a barbell across the hips only with adequate padding.',
    },
    {
        'name': 'Bulgarian Split Squat',
        'category': 'legs',
        'difficulty': 'advanced',
        'equipment': 'Bench + Dumbbells',
        'goal': 'strength',
        'default_reps': 8, 'default_sets': 3, 'duration_min': 8, 'calories_per_set': 14,
        'target_muscles': 'Quads, Glutes, Adductors, Core',
        'description': 'A demanding single-leg exercise that exposes and fixes strength imbalances.',
        'steps': "Setup: Stand a stride length in front of a bench, place the top of one foot on the bench behind you.\nMovement: Lower until the front thigh is parallel to the floor, then drive up through the front heel.",
        'form_tips': "Keep the front knee tracking over the toes and torso upright.",
        'breathing': 'Inhale lowering, exhale standing up.',
        'common_mistakes': 'Letting the front knee collapse inward or the torso pitch forward.',
        'safety': 'Start with bodyweight to nail balance before adding load.',
    },
    {
        'name': 'Calf Raise',
        'category': 'legs',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight or Dumbbells, Optional Step',
        'goal': 'general',
        'default_reps': 20, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 5,
        'target_muscles': 'Calves (Gastrocnemius, Soleus)',
        'description': 'The simplest way to build the calf muscles that power every step, run, and jump.',
        'steps': "Setup: Stand on a flat surface (or the edge of a step) with feet hip-width.\nMovement: Rise onto the balls of the feet, pause at the top, then lower the heels under control.",
        'form_tips': "Move slowly through the full range; pause at the top and bottom for max stimulus.",
        'breathing': 'Exhale rising, inhale lowering.',
        'common_mistakes': 'Bouncing at the bottom and using momentum to skip the stretch.',
        'safety': 'Use a wall or rail for balance if needed.',
    },

    # ---------- CORE ----------
    {
        'name': 'Plank',
        'category': 'core',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight',
        'goal': 'general',
        'default_reps': 1, 'default_sets': 3, 'duration_min': 3, 'calories_per_set': 4,
        'target_muscles': 'Core, Shoulders, Glutes',
        'description': 'An isometric core hold that builds endurance and total-body stability.',
        'steps': "Setup: Forearms on the floor, elbows under shoulders, body in a straight line.\nMovement: Hold the position, bracing the abs and squeezing the glutes.",
        'form_tips': "Don't let the hips sag or pike up; aim for a long, strong line.",
        'breathing': 'Breathe slowly and steadily through the nose and mouth.',
        'common_mistakes': 'Sagging the hips or holding the breath.',
        'safety': 'Drop to the knees if form breaks; stop if you feel lower-back pain.',
    },
    {
        'name': 'Hollow Hold',
        'category': 'core',
        'difficulty': 'intermediate',
        'equipment': 'Bodyweight',
        'goal': 'strength',
        'default_reps': 1, 'default_sets': 3, 'duration_min': 3, 'calories_per_set': 6,
        'target_muscles': 'Deep Core, Hip Flexors, Quads',
        'description': 'A gymnastic core hold that builds the kind of stability needed for muscle-ups and toes-to-bar.',
        'steps': "Setup: Lie on your back, arms extended overhead, legs straight and together.\nMovement: Press the lower back into the floor, lift the shoulders and legs off the ground into a shallow banana shape, and hold.",
        'form_tips': "The lower back MUST stay glued to the floor — bend the knees or arms to scale the difficulty.",
        'breathing': "Steady, controlled breaths — don't hold.",
        'common_mistakes': 'Letting the lower back arch off the floor.',
        'safety': 'Reduce the lever by bending the knees if the back lifts.',
    },
    {
        'name': 'Hanging Leg Raise',
        'category': 'core',
        'difficulty': 'advanced',
        'equipment': 'Pull-Up Bar',
        'goal': 'strength',
        'default_reps': 10, 'default_sets': 3, 'duration_min': 5, 'calories_per_set': 10,
        'target_muscles': 'Abs, Hip Flexors, Forearms, Lats',
        'description': 'A serious ab exercise that demands grip, lat strength, and hip control.',
        'steps': "Setup: Hang from a bar with an overhand grip, shoulders engaged.\nMovement: Raise the legs to at least parallel (or all the way to the bar) by curling the hips up, then lower with control.",
        'form_tips': "Curl the pelvis up — don't just lift the legs. Avoid swinging.",
        'breathing': 'Exhale lifting, inhale lowering.',
        'common_mistakes': 'Swinging the body to generate momentum.',
        'safety': 'Use a neutral grip or straps if the forearms fatigue before the abs.',
    },
    {
        'name': 'Russian Twist',
        'category': 'core',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight or Dumbbell/Plate',
        'goal': 'general',
        'default_reps': 20, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 7,
        'target_muscles': 'Obliques, Abs, Hip Flexors',
        'description': 'A rotational core exercise that targets the obliques and teaches trunk control.',
        'steps': "Setup: Sit on the floor with knees bent, heels down, torso leaned back ~45°.\nMovement: Rotate the shoulders side to side, touching the weight (or hands) to the floor on each side.",
        'form_tips': "Keep the chest proud and the spine long — don't slouch.",
        'breathing': 'Exhale rotating, inhale returning to center.',
        'common_mistakes': 'Rounding the back or twisting only with the arms.',
        'safety': 'Lift the feet off the floor to progress, or keep them down to regress.',
    },
    {
        'name': 'Dead Bug',
        'category': 'core',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight',
        'goal': 'mobility',
        'default_reps': 10, 'default_sets': 3, 'duration_min': 3, 'calories_per_set': 5,
        'target_muscles': 'Deep Core, Hip Flexors, Shoulders',
        'description': 'A controlled anti-extension exercise that teaches core bracing under moving limbs.',
        'steps': "Setup: Lie on your back, arms extended toward the ceiling, knees and hips at 90°.\nMovement: Slowly extend the opposite arm and leg toward the floor, keeping the lower back pressed down, then return and switch sides.",
        'form_tips': "Move slowly — the goal is core control, not speed.",
        'breathing': 'Exhale extending, inhale returning.',
        'common_mistakes': 'Letting the lower back arch as the limbs extend.',
        'safety': 'Reduce the range of motion if the back starts to lift.',
    },

    # ---------- CARDIO ----------
    {
        'name': 'Jumping Jacks',
        'category': 'cardio',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight',
        'goal': 'weight_loss',
        'default_reps': 30, 'default_sets': 3, 'duration_min': 3, 'calories_per_set': 9,
        'target_muscles': 'Full Body, Cardiovascular System',
        'description': 'A classic warm-up and conditioning move that elevates the heart rate fast.',
        'steps': "Setup: Stand tall with arms by your sides.\nMovement: Jump the feet out wide while raising the arms overhead, then jump back to the start.",
        'form_tips': "Stay light on the toes; keep a smooth, steady rhythm.",
        'breathing': 'Breathe in through the nose and out through the mouth at a steady pace.',
        'common_mistakes': 'Landing heavily on the heels or losing rhythm.',
        'safety': 'Skip the impact if you have joint issues — try step jacks instead.',
    },
    {
        'name': 'Burpee',
        'category': 'cardio',
        'difficulty': 'advanced',
        'equipment': 'Bodyweight',
        'goal': 'weight_loss',
        'default_reps': 10, 'default_sets': 4, 'duration_min': 6, 'calories_per_set': 15,
        'target_muscles': 'Full Body, Cardiovascular System',
        'description': 'A high-intensity full-body move that builds conditioning and power.',
        'steps': "Setup: Stand tall.\nMovement: Drop to a squat, kick the feet back into a plank, perform a push-up (optional), jump the feet back to the squat, then explode up into a jump.",
        'form_tips': "Move at a controlled pace — sloppy burpees invite injury and waste energy.",
        'breathing': 'Establish a steady rhythm; exhale on the jump.',
        'common_mistakes': 'Sagging in the plank or skipping the stand-up jump to save energy.',
        'safety': 'Remove the push-up and jump for a low-impact regression.',
    },
    {
        'name': 'High Knees',
        'category': 'cardio',
        'difficulty': 'beginner',
        'equipment': 'Bodyweight',
        'goal': 'endurance',
        'default_reps': 40, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 11,
        'target_muscles': 'Hip Flexors, Quads, Calves, Cardiovascular System',
        'description': 'A simple, scalable conditioning drill that elevates heart rate and warms the hips.',
        'steps': "Setup: Stand tall with feet hip-width.\nMovement: Run in place, driving each knee up to hip height, pumping the arms in opposition.",
        'form_tips': "Stay on the balls of the feet; keep the torso tall.",
        'breathing': 'Steady nasal or mouth breathing — match your cadence.',
        'common_mistakes': 'Leaning back or letting the heels slam the floor.',
        'safety': 'Slow the pace if impact bothers the knees or shins.',
    },
    {
        'name': 'Mountain Climber',
        'category': 'cardio',
        'difficulty': 'intermediate',
        'equipment': 'Bodyweight',
        'goal': 'weight_loss',
        'default_reps': 30, 'default_sets': 3, 'duration_min': 4, 'calories_per_set': 12,
        'target_muscles': 'Core, Hip Flexors, Shoulders, Cardiovascular System',
        'description': 'A plank-based conditioning move that lights up the core and elevates the heart rate.',
        'steps': "Setup: Begin in a high plank, hands under shoulders, body in a straight line.\nMovement: Drive one knee toward the chest, then quickly switch legs in a running motion.",
        'form_tips': "Keep the hips low and the core tight — don't pike up.",
        'breathing': 'Breathe steadily through the movement.',
        'common_mistakes': 'Bouncing the hips up or rushing without control.',
        'safety': 'Slow down and widen the feet for a beginner-friendly version.',
    },
    {
        'name': 'Jump Rope',
        'category': 'cardio',
        'difficulty': 'intermediate',
        'equipment': 'Jump Rope',
        'goal': 'weight_loss',
        'default_reps': 1, 'default_sets': 5, 'duration_min': 8, 'calories_per_set': 14,
        'target_muscles': 'Calves, Shoulders, Cardiovascular System',
        'description': 'A timeless conditioning tool that builds footwork, calf endurance, and aerobic capacity.',
        'steps': "Setup: Hold the rope handles at hip height, elbows close to the body.\nMovement: Rotate the rope with the wrists and hop on the balls of the feet.",
        'form_tips': "Wrist rotation, not arm swings. Stay light on the toes.",
        'breathing': 'Establish a steady rhythm; breathe through the nose when possible.',
        'common_mistakes': 'Swinging with the whole arm or jumping too high.',
        'safety': 'Use a cushioned surface to protect shins and knees.',
    },
    {
        'name': 'Box Jump',
        'category': 'cardio',
        'difficulty': 'advanced',
        'equipment': 'Plyo Box',
        'goal': 'strength',
        'default_reps': 6, 'default_sets': 4, 'duration_min': 6, 'calories_per_set': 14,
        'target_muscles': 'Quads, Glutes, Calves, Core',
        'description': 'A power-focused plyometric move that builds explosive leg drive.',
        'steps': "Setup: Stand facing a sturdy box, feet shoulder-width.\nMovement: Hinge and swing the arms, jump onto the box landing softly with both feet, then stand tall to finish the rep.",
        'form_tips': "Land in a partial squat on top — never jump down and rebound on the same rep.",
        'breathing': 'Exhale on the jump, inhale on the step-down.',
        'common_mistakes': 'Landing stiff-legged or jumping with the knees collapsing inward.',
        'safety': "Step down, don't jump down; choose a box height you can land safely on.",
    },
    {
        'name': 'Rowing Ergometer',
        'category': 'cardio',
        'difficulty': 'intermediate',
        'equipment': 'Rower',
        'goal': 'endurance',
        'default_reps': 1, 'default_sets': 4, 'duration_min': 12, 'calories_per_set': 18,
        'target_muscles': 'Back, Legs, Arms, Cardiovascular System',
        'description': 'A low-impact, full-body conditioning tool that builds aerobic base and total-body power.',
        'steps': "Setup: Strap feet in, sit tall, grip the handle just past the flywheel.\nMovement: Drive the legs, swing the torso, then pull the arms — reverse the order on the recovery.",
        'form_tips': "Sequence is legs → back → arms on the drive, and arms → back → legs on the recovery.",
        'breathing': 'Steady rhythm — one breath per stroke at moderate intensities.',
        'common_mistakes': 'Pulling with the arms before the legs open up.',
        'safety': 'Keep a moderate stroke rate when learning technique.',
    },
]


class Command(BaseCommand):
    help = 'Seed the exercise library with a comprehensive set of movements.'

    def handle(self, *args, **options):
        self.stdout.write('Seeding exercise library...')

        from django.utils.text import slugify

        created = 0
        updated = 0
        for data in EXERCISES:
            slug = slugify(data['name'])
            _, was_created = Exercise.objects.update_or_create(
                slug=slug,
                defaults={**data, 'slug': slug},
            )
            if was_created:
                created += 1
            else:
                updated += 1

        total = Exercise.objects.count()
        self.stdout.write(self.style.SUCCESS(
            f'  + {total} exercises ready ({created} new, {updated} updated)'
        ))

        from collections import Counter
        by_category = Counter(Exercise.objects.values_list('category', flat=True))
        by_goal = Counter(Exercise.objects.values_list('goal', flat=True))
        by_difficulty = Counter(Exercise.objects.values_list('difficulty', flat=True))
        self.stdout.write(f'  Categories: {dict(by_category)}')
        self.stdout.write(f'  Goals:      {dict(by_goal)}')
        self.stdout.write(f'  Levels:     {dict(by_difficulty)}')
        self.stdout.write(self.style.SUCCESS('Exercise library seeded.'))
