# Generated by Django 5.0.6 on 2026-06-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspirationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.CharField(max_length=240)),
                ('icon', models.CharField(default='💪', help_text='Single emoji', max_length=8)),
                ('accent', models.CharField(default='emerald', help_text='CSS accent class (emerald/cyan/amber/violet/rose/sky)', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Inspiration categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FitnessIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('nickname', models.CharField(blank=True, max_length=120)),
                ('short_bio', models.CharField(max_length=240)),
                ('bio', models.TextField(help_text='Markdown-free paragraph biography')),
                ('image_url', models.URLField(blank=True)),
                ('portrait_url', models.URLField(blank=True, help_text='Optional darker portrait crop')),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('born', models.CharField(blank=True, max_length=80)),
                ('discipline', models.CharField(blank=True, max_length=120)),
                ('achievements', models.TextField(blank=True, help_text='One achievement per line; renders as a bullet list')),
                ('training_tips', models.TextField(blank=True, help_text='Practical training/life tips from this icon')),
                ('signature_quote', models.CharField(blank=True, max_length=400)),
                ('video_url', models.URLField(blank=True, help_text='YouTube embed URL')),
                ('video_title', models.CharField(blank=True, max_length=200)),
                ('instagram_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icons', to='inspiration.inspirationcategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MotivationQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='inspiration.inspirationcategory')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='inspiration.fitnessicon')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
