# Generated by Django 5.0.6 on 2026-06-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessicon',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='fitnessicon',
            name='portrait',
            field=models.ImageField(blank=True, help_text='Upload a portrait', upload_to='icons/portraits/'),
        ),
        migrations.AlterField(
            model_name='fitnessicon',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL (e.g. Unsplash)'),
        ),
    ]
